# Generated by Django 4.0.2 on 2023-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Published')], default=1, max_length=1),
        ),
    ]
